'use strict';

/*
  DeafHire — Table de correspondance ASL → Français (LSF)
  =========================================================
  Les signes WLASL sont en anglais (ASL). Ce dictionnaire mappe
  chaque gloss ASL vers son équivalent conceptuel en français,
  tel qu'il serait exprimé en LSF.

  Note linguistique : ASL et LSF sont deux langues distinctes.
  Ce n'est pas une traduction signe-à-signe, mais une localisation
  du concept détecté (le sens du signe) vers le français.

  Couverture : ~500 entrées — vocabulaire WLASL le plus fréquent.
*/

const ASL_LSF_MAP = {

  // ── Salutations & politesse ──────────────────────────────────
  'hello':          'Bonjour',
  'hi':             'Bonjour',
  'goodbye':        'Au revoir',
  'bye':            'Au revoir',
  'good morning':   'Bonjour',
  'good afternoon': 'Bon après-midi',
  'good night':     'Bonne nuit',
  'good evening':   'Bonsoir',
  'thank you':      'Merci',
  'thanks':         'Merci',
  'please':         'S\'il vous plaît',
  'sorry':          'Désolé',
  'excuse me':      'Excusez-moi',
  'you\'re welcome':'De rien',
  'welcome':        'Bienvenue',

  // ── Réponses de base ─────────────────────────────────────────
  'yes':            'Oui',
  'no':             'Non',
  'maybe':          'Peut-être',
  'ok':             'D\'accord',
  'fine':           'Bien / D\'accord',
  'sure':           'Bien sûr',
  'right':          'C\'est juste',
  'wrong':          'Faux / Tort',
  'true':           'Vrai',
  'false':          'Faux',

  // ── Pronoms ──────────────────────────────────────────────────
  'i':              'Je / Moi',
  'me':             'Je / Moi',
  'myself':         'Moi-même',
  'you':            'Tu / Vous',
  'yourself':       'Toi-même',
  'he':             'Il',
  'she':            'Elle',
  'him':            'Lui',
  'her':            'Elle',
  'we':             'Nous',
  'us':             'Nous',
  'they':           'Ils / Elles',
  'them':           'Eux / Elles',
  'it':             'Ça / Il',
  'this':           'Ceci / Ce',
  'that':           'Ça / Cela',
  'my':             'Mon / Ma',
  'your':           'Ton / Votre',
  'his':            'Son',
  'her-poss':       'Sa',
  'our':            'Notre',
  'their':          'Leur',

  // ── Questions ────────────────────────────────────────────────
  'what':           'Quoi / Que',
  'where':          'Où',
  'when':           'Quand',
  'who':            'Qui',
  'why':            'Pourquoi',
  'how':            'Comment',
  'how many':       'Combien',
  'how much':       'Combien',
  'which':          'Lequel / Quel',
  'question':       'Question',
  'ask':            'Demander',

  // ── Chiffres ─────────────────────────────────────────────────
  'one':            'Un',
  'two':            'Deux',
  'three':          'Trois',
  'four':           'Quatre',
  'five':           'Cinq',
  'six':            'Six',
  'seven':          'Sept',
  'eight':          'Huit',
  'nine':           'Neuf',
  'ten':            'Dix',
  'eleven':         'Onze',
  'twelve':         'Douze',
  'thirteen':       'Treize',
  'fourteen':       'Quatorze',
  'fifteen':        'Quinze',
  'twenty':         'Vingt',
  'thirty':         'Trente',
  'hundred':        'Cent',
  'thousand':       'Mille',
  'million':        'Million',
  'zero':           'Zéro',
  'number':         'Nombre',
  'first':          'Premier',
  'second':         'Deuxième',
  'third':          'Troisième',
  'last':           'Dernier',

  // ── Couleurs ─────────────────────────────────────────────────
  'red':            'Rouge',
  'blue':           'Bleu',
  'green':          'Vert',
  'yellow':         'Jaune',
  'orange':         'Orange',
  'purple':         'Violet',
  'pink':           'Rose',
  'white':          'Blanc',
  'black':          'Noir',
  'brown':          'Marron',
  'gray':           'Gris',
  'color':          'Couleur',

  // ── Famille ──────────────────────────────────────────────────
  'family':         'Famille',
  'mother':         'Mère',
  'mom':            'Maman',
  'father':         'Père',
  'dad':            'Papa',
  'brother':        'Frère',
  'sister':         'Sœur',
  'son':            'Fils',
  'daughter':       'Fille',
  'baby':           'Bébé',
  'child':          'Enfant',
  'children':       'Enfants',
  'boy':            'Garçon',
  'girl':           'Fille',
  'man':            'Homme',
  'woman':          'Femme',
  'husband':        'Mari',
  'wife':           'Femme',
  'grandfather':    'Grand-père',
  'grandmother':    'Grand-mère',
  'uncle':          'Oncle',
  'aunt':           'Tante',
  'cousin':         'Cousin / Cousine',
  'nephew':         'Neveu',
  'niece':          'Nièce',
  'people':         'Personnes / Gens',
  'person':         'Personne',

  // ── Professionnel & entretien ─────────────────────────────────
  'work':           'Travail',
  'job':            'Emploi / Travail',
  'career':         'Carrière',
  'experience':     'Expérience',
  'skill':          'Compétence',
  'ability':        'Capacité',
  'study':          'Formation / Étude',
  'learn':          'Apprendre / Formation',
  'education':      'Formation / Éducation',
  'school':         'École / Formation',
  'college':        'Université',
  'university':     'Université',
  'graduate':       'Diplômé',
  'understand':     'Comprendre',
  'again':          'Répéter / Encore',
  'repeat':         'Répéter',
  'team':           'Équipe',
  'group':          'Groupe / Équipe',
  'together':       'Ensemble',
  'future':         'Futur',
  'will':           'Futur / Vouloir',
  'plan':           'Projet / Plan',
  'goal':           'Objectif',
  'project':        'Projet',
  'meeting':        'Réunion',
  'interview':      'Entretien',
  'company':        'Entreprise',
  'office':         'Bureau',
  'manager':        'Responsable',
  'boss':           'Patron',
  'employee':       'Employé',
  'salary':         'Salaire',
  'hire':           'Embaucher',
  'fired':          'Licencié',
  'resign':         'Démissionner',
  'retire':         'Retraite',
  'responsible':    'Responsable',
  'leader':         'Leader',
  'professional':   'Professionnel',
  'engineer':       'Ingénieur',
  'developer':      'Développeur',
  'teacher':        'Professeur',
  'student':        'Étudiant',
  'doctor':         'Médecin',
  'nurse':          'Infirmier/ère',
  'lawyer':         'Avocat',
  'police':         'Police',
  'chef':           'Cuisinier',
  'artist':         'Artiste',
  'scientist':      'Scientifique',
  'volunteer':      'Bénévole',

  // ── Actions / Verbes courants ─────────────────────────────────
  'go':             'Aller',
  'come':           'Venir',
  'walk':           'Marcher',
  'run':            'Courir',
  'sit':            'S\'asseoir',
  'stand':          'Se lever / Debout',
  'stop':           'Arrêter',
  'start':          'Commencer',
  'finish':         'Finir / Terminé',
  'open':           'Ouvrir',
  'close':          'Fermer',
  'give':           'Donner',
  'take':           'Prendre',
  'want':           'Vouloir',
  'need':           'Avoir besoin',
  'like':           'Aimer / Apprécier',
  'love':           'Aimer / Amour',
  'hate':           'Détester',
  'think':          'Penser',
  'know':           'Savoir / Connaître',
  'remember':       'Se souvenir',
  'forget':         'Oublier',
  'see':            'Voir',
  'look':           'Regarder',
  'watch':          'Regarder',
  'listen':         'Écouter',
  'hear':           'Entendre',
  'talk':           'Parler',
  'speak':          'Parler',
  'say':            'Dire',
  'tell':           'Dire / Raconter',
  'ask':            'Demander',
  'answer':         'Répondre',
  'help':           'Aider / Aide',
  'make':           'Faire / Fabriquer',
  'do':             'Faire',
  'play':           'Jouer',
  'write':          'Écrire',
  'read':           'Lire',
  'draw':           'Dessiner',
  'paint':          'Peindre',
  'sing':           'Chanter',
  'dance':          'Danser',
  'swim':           'Nager',
  'jump':           'Sauter',
  'drive':          'Conduire',
  'cook':           'Cuisiner',
  'eat':            'Manger',
  'drink':          'Boire',
  'sleep':          'Dormir',
  'wake':           'Se réveiller',
  'wait':           'Attendre',
  'visit':          'Rendre visite',
  'meet':           'Rencontrer',
  'find':           'Trouver',
  'lose':           'Perdre',
  'win':            'Gagner',
  'buy':            'Acheter',
  'sell':           'Vendre',
  'pay':            'Payer',
  'spend':          'Dépenser',
  'save':           'Économiser / Sauvegarder',
  'change':         'Changer',
  'move':           'Bouger / Déménager',
  'put':            'Mettre / Poser',
  'bring':          'Apporter',
  'send':           'Envoyer',
  'receive':        'Recevoir',
  'keep':           'Garder',
  'leave':          'Partir / Laisser',
  'stay':           'Rester',
  'live':           'Vivre / Habiter',
  'die':            'Mourir',
  'born':           'Né / Naissance',
  'grow':           'Grandir',
  'become':         'Devenir',
  'try':            'Essayer',
  'practice':       'Pratiquer / S\'entraîner',
  'use':            'Utiliser',
  'show':           'Montrer',
  'explain':        'Expliquer',
  'teach':          'Enseigner',
  'train':          'Former / Entraîner',
  'test':           'Tester',
  'choose':         'Choisir',
  'decide':         'Décider',
  'agree':          'Être d\'accord',
  'disagree':       'Ne pas être d\'accord',
  'support':        'Soutenir',
  'manage':         'Gérer',
  'create':         'Créer',
  'build':          'Construire',
  'design':         'Concevoir',
  'fix':            'Réparer',
  'break':          'Casser / Pause',
  'check':          'Vérifier',
  'sign':           'Signe / Signer',
  'have':           'Avoir',
  'own':            'Posséder',
  'share':          'Partager',

  // ── Adjectifs ────────────────────────────────────────────────
  'good':           'Bon / Bien',
  'bad':            'Mauvais / Mal',
  'better':         'Meilleur',
  'best':           'Le meilleur',
  'worst':          'Le pire',
  'great':          'Super / Excellent',
  'perfect':        'Parfait',
  'nice':           'Sympa / Bien',
  'beautiful':      'Beau / Belle',
  'pretty':         'Joli',
  'ugly':           'Laid',
  'cool':           'Cool',
  'funny':          'Drôle / Amusant',
  'happy':          'Heureux / Content',
  'sad':            'Triste',
  'angry':          'En colère',
  'afraid':         'Peur / Effrayé',
  'surprised':      'Surpris',
  'tired':          'Fatigué',
  'sick':           'Malade',
  'hurt':           'Blessé / Avoir mal',
  'healthy':        'En bonne santé',
  'hungry':         'Faim',
  'thirsty':        'Soif',
  'full':           'Rassasié / Plein',
  'hot':            'Chaud',
  'cold':           'Froid',
  'warm':           'Tiède / Chaud',
  'big':            'Grand',
  'small':          'Petit',
  'large':          'Grand / Large',
  'little':         'Petit / Peu',
  'tall':           'Grand (taille)',
  'short':          'Petit / Court',
  'long':           'Long',
  'fast':           'Rapide / Vite',
  'slow':           'Lent',
  'hard':           'Difficile / Dur',
  'easy':           'Facile',
  'clean':          'Propre / Nettoyer',
  'dirty':          'Sale',
  'new':            'Nouveau',
  'old':            'Vieux / Ancien',
  'different':      'Différent',
  'same':           'Pareil / Même',
  'many':           'Beaucoup',
  'some':           'Quelques',
  'few':            'Peu',
  'all':            'Tout / Tous',
  'none':           'Aucun / Rien',
  'other':          'Autre',
  'only':           'Seulement',
  'often':          'Souvent',
  'always':         'Toujours',
  'never':          'Jamais',
  'sometimes':      'Parfois',
  'very':           'Très',
  'really':         'Vraiment',
  'thin':           'Mince',
  'fat':            'Gros',
  'deaf':           'Sourd',
  'hearing':        'Entendant',
  'mute':           'Muet',
  'blind':          'Aveugle',
  'important':      'Important',
  'interesting':    'Intéressant',
  'boring':         'Ennuyeux',
  'free':           'Libre / Gratuit',
  'busy':           'Occupé',
  'ready':          'Prêt',
  'late':           'En retard',
  'early':          'Tôt / En avance',
  'special':        'Spécial',
  'popular':        'Populaire',
  'lucky':          'Chanceux',
  'smart':          'Intelligent',
  'funny-adj':      'Drôle',
  'crazy':          'Fou',
  'serious':        'Sérieux',

  // ── Temps ────────────────────────────────────────────────────
  'time':           'Temps / Heure',
  'now':            'Maintenant',
  'today':          'Aujourd\'hui',
  'tomorrow':       'Demain',
  'yesterday':      'Hier',
  'morning':        'Matin',
  'afternoon':      'Après-midi',
  'evening':        'Soir',
  'night':          'Nuit',
  'week':           'Semaine',
  'month':          'Mois',
  'year':           'Année',
  'day':            'Jour',
  'hour':           'Heure',
  'minute':         'Minute',
  'second':         'Seconde',
  'before':         'Avant',
  'after':          'Après',
  'soon':           'Bientôt',
  'later':          'Plus tard',
  'past':           'Passé',
  'present':        'Présent',
  'summer':         'Été',
  'winter':         'Hiver',
  'spring':         'Printemps',
  'fall':           'Automne',
  'weekend':        'Week-end',
  'holiday':        'Vacances / Fête',
  'birthday':       'Anniversaire',

  // ── Lieux ────────────────────────────────────────────────────
  'home':           'Maison',
  'house':          'Maison',
  'room':           'Chambre / Pièce',
  'door':           'Porte',
  'window':         'Fenêtre',
  'kitchen':        'Cuisine',
  'bathroom':       'Salle de bain',
  'bedroom':        'Chambre',
  'garden':         'Jardin',
  'city':           'Ville',
  'town':           'Ville / Commune',
  'country':        'Pays',
  'street':         'Rue',
  'road':           'Route',
  'store':          'Magasin',
  'shop':           'Boutique',
  'restaurant':     'Restaurant',
  'hospital':       'Hôpital',
  'park':           'Parc',
  'church':         'Église',
  'bank':           'Banque',
  'library':        'Bibliothèque',
  'gym':            'Salle de sport',
  'hotel':          'Hôtel',
  'airport':        'Aéroport',
  'station':        'Gare',
  'under':          'Sous',
  'up':             'En haut',
  'down':           'En bas',
  'in':             'Dans',
  'out':            'Dehors / Sortir',
  'here':           'Ici',
  'there':          'Là-bas',

  // ── Nourriture & boissons ─────────────────────────────────────
  'food':           'Nourriture',
  'water':          'Eau',
  'coffee':         'Café',
  'tea':            'Thé',
  'milk':           'Lait',
  'juice':          'Jus',
  'beer':           'Bière',
  'bread':          'Pain',
  'rice':           'Riz',
  'meat':           'Viande',
  'chicken':        'Poulet',
  'fish':           'Poisson',
  'fruit':          'Fruit',
  'vegetable':      'Légume',
  'apple':          'Pomme',
  'banana':         'Banane',
  'orange-fruit':   'Orange',
  'pizza':          'Pizza',
  'candy':          'Bonbon / Sucre',
  'cake':           'Gâteau',
  'ice cream':      'Glace',
  'egg':            'Œuf',
  'soup':           'Soupe',
  'sandwich':       'Sandwich',

  // ── Transport ────────────────────────────────────────────────
  'car':            'Voiture',
  'bus':            'Bus',
  'train':          'Train',
  'plane':          'Avion',
  'bike':           'Vélo',
  'boat':           'Bateau',
  'taxi':           'Taxi',
  'drive':          'Conduire',
  'travel':         'Voyager',

  // ── Technologie ──────────────────────────────────────────────
  'phone':          'Téléphone',
  'computer':       'Ordinateur',
  'internet':       'Internet',
  'email':          'Email / Courriel',
  'video':          'Vidéo',
  'camera':         'Caméra',
  'tv':             'Télévision',
  'radio':          'Radio',
  'music':          'Musique',
  'movie':          'Film',
  'book':           'Livre',
  'paper':          'Papier',
  'money':          'Argent',
  'key':            'Clé',

  // ── Nature & animaux ─────────────────────────────────────────
  'animal':         'Animal',
  'dog':            'Chien',
  'cat':            'Chat',
  'bird':           'Oiseau',
  'fish-animal':    'Poisson',
  'horse':          'Cheval',
  'cow':            'Vache',
  'tree':           'Arbre',
  'flower':         'Fleur',
  'sun':            'Soleil',
  'moon':           'Lune',
  'star':           'Étoile',
  'rain':           'Pluie',
  'snow':           'Neige',
  'wind':           'Vent',
  'fire':           'Feu',
  'water-nature':   'Eau',
  'mountain':       'Montagne',
  'river':          'Rivière',
  'ocean':          'Océan / Mer',

  // ── Corps ────────────────────────────────────────────────────
  'hand':           'Main',
  'arm':            'Bras',
  'head':           'Tête',
  'face':           'Visage',
  'eye':            'Œil',
  'ear':            'Oreille',
  'nose':           'Nez',
  'mouth':          'Bouche',
  'hair':           'Cheveux',
  'heart':          'Cœur',
  'body':           'Corps',
  'back':           'Dos',
  'leg':            'Jambe',
  'foot':           'Pied',
  'finger':         'Doigt',

  // ── Vêtements ────────────────────────────────────────────────
  'clothes':        'Vêtements',
  'shirt':          'Chemise',
  'dress':          'Robe',
  'coat':           'Manteau',
  'shoes':          'Chaussures',
  'hat':            'Chapeau',
  'glasses':        'Lunettes',

  // ── Prépositions & connecteurs ────────────────────────────────
  'and':            'Et',
  'or':             'Ou',
  'but':            'Mais',
  'because':        'Parce que',
  'if':             'Si',
  'with':           'Avec',
  'without':        'Sans',
  'for':            'Pour',
  'about':          'À propos',
  'also':           'Aussi',
  'not':            'Ne pas / Non',
  'nothing':        'Rien',
  'something':      'Quelque chose',
  'everything':     'Tout',
  'enough':         'Assez / Suffisant',
  'more':           'Plus',
  'less':           'Moins',
  'again':          'Encore / Répéter',
  'together':       'Ensemble',
  'suppose':        'Supposer / Si',
  'until':          'Jusqu\'à',
  'let':            'Laisser / Permettre',

  // ── Sports & loisirs ─────────────────────────────────────────
  'football':       'Football',
  'basketball':     'Basketball',
  'baseball':       'Baseball',
  'soccer':         'Football',
  'tennis':         'Tennis',
  'gym':            'Gym / Sport',
  'sport':          'Sport',
  'game':           'Jeu',
  'fun':            'Amusement / Fun',
  'enjoy':          'Apprécier / Profiter',
  'visit':          'Visiter',

  // ── Émotions & état ──────────────────────────────────────────
  'feel':           'Ressentir',
  'emotion':        'Émotion',
  'worry':          'S\'inquiéter',
  'hope':           'Espoir / Espérer',
  'trust':          'Confiance',
  'proud':          'Fier',
  'shame':          'Honte',
  'bored':          'Ennuyé',
  'excited':        'Excité / Enthousiaste',
  'nervous':        'Nerveux',
  'comfortable':    'À l\'aise',
  'alone':          'Seul',
  'together-emo':   'Ensemble',
  'enjoy':          'Apprécier',
  'hate':           'Détester',
  'miss':           'Manquer / Rater',

  // ── Divers importants ────────────────────────────────────────
  'name':           'Nom',
  'age':            'Âge',
  'address':        'Adresse',
  'language':       'Langue',
  'sign language':  'Langue des signes',
  'french':         'Français',
  'english':        'Anglais',
  'american':       'Américain',
  'france':         'France',
  'america':        'Amérique / États-Unis',
  'friend':         'Ami',
  'neighbor':       'Voisin',
  'stranger':       'Étranger / Inconnu',
  'class':          'Classe / Cours',
  'lesson':         'Leçon / Cours',
  'test':           'Test / Examen',
  'exam':           'Examen',
  'grade':          'Note',
  'success':        'Succès',
  'fail':           'Échouer',
  'problem':        'Problème',
  'solution':       'Solution',
  'idea':           'Idée',
  'opinion':        'Opinion / Avis',
  'information':    'Information',
  'news':           'Nouvelles / Actualités',
  'story':          'Histoire',
  'example':        'Exemple',
  'reason':         'Raison',
  'result':         'Résultat',
  'answer':         'Réponse',
  'message':        'Message',
  'letter':         'Lettre',
  'word':           'Mot',
  'sentence':       'Phrase',
  'topic':          'Sujet',

};

/*
  Traduit un gloss ASL vers le français.
  Si inconnu, retourne le gloss avec un indicateur (ASL).
*/
function translateASLtoFrench(gloss) {
  if (!gloss) return gloss;
  const key = gloss.toLowerCase().trim();
  return ASL_LSF_MAP[key] || (gloss.charAt(0).toUpperCase() + gloss.slice(1));
}

window.ASL_LSF_MAP         = ASL_LSF_MAP;
window.translateASLtoFrench = translateASLtoFrench;
